// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: algorithm_service.proto

package org.example.madeinha.global.gRPC;

public final class AlgorithmServiceOuterClass {
  private AlgorithmServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlgorithmRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:algorithm.AlgorithmRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string json_input = 1;</code>
     * @return The jsonInput.
     */
    java.lang.String getJsonInput();
    /**
     * <code>string json_input = 1;</code>
     * @return The bytes for jsonInput.
     */
    com.google.protobuf.ByteString
        getJsonInputBytes();
  }
  /**
   * Protobuf type {@code algorithm.AlgorithmRequest}
   */
  public static final class AlgorithmRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:algorithm.AlgorithmRequest)
      AlgorithmRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlgorithmRequest.newBuilder() to construct.
    private AlgorithmRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlgorithmRequest() {
      jsonInput_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlgorithmRequest();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlgorithmServiceOuterClass.AlgorithmRequest.class, AlgorithmServiceOuterClass.AlgorithmRequest.Builder.class);
    }

    public static final int JSON_INPUT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jsonInput_ = "";
    /**
     * <code>string json_input = 1;</code>
     * @return The jsonInput.
     */
    @java.lang.Override
    public java.lang.String getJsonInput() {
      java.lang.Object ref = jsonInput_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonInput_ = s;
        return s;
      }
    }
    /**
     * <code>string json_input = 1;</code>
     * @return The bytes for jsonInput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonInputBytes() {
      java.lang.Object ref = jsonInput_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonInput_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonInput_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonInput_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonInput_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonInput_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AlgorithmServiceOuterClass.AlgorithmRequest)) {
        return super.equals(obj);
      }
      AlgorithmServiceOuterClass.AlgorithmRequest other = (AlgorithmServiceOuterClass.AlgorithmRequest) obj;

      if (!getJsonInput()
          .equals(other.getJsonInput())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_INPUT_FIELD_NUMBER;
      hash = (53 * hash) + getJsonInput().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AlgorithmServiceOuterClass.AlgorithmRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static AlgorithmServiceOuterClass.AlgorithmRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AlgorithmServiceOuterClass.AlgorithmRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AlgorithmServiceOuterClass.AlgorithmRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code algorithm.AlgorithmRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:algorithm.AlgorithmRequest)
        AlgorithmServiceOuterClass.AlgorithmRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlgorithmServiceOuterClass.AlgorithmRequest.class, AlgorithmServiceOuterClass.AlgorithmRequest.Builder.class);
      }

      // Construct using org.example.madeinha.global.gRPC.AlgorithmServiceOuterClass.AlgorithmRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        jsonInput_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmRequest_descriptor;
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmRequest getDefaultInstanceForType() {
        return AlgorithmServiceOuterClass.AlgorithmRequest.getDefaultInstance();
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmRequest build() {
        AlgorithmServiceOuterClass.AlgorithmRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmRequest buildPartial() {
        AlgorithmServiceOuterClass.AlgorithmRequest result = new AlgorithmServiceOuterClass.AlgorithmRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(AlgorithmServiceOuterClass.AlgorithmRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.jsonInput_ = jsonInput_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlgorithmServiceOuterClass.AlgorithmRequest) {
          return mergeFrom((AlgorithmServiceOuterClass.AlgorithmRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlgorithmServiceOuterClass.AlgorithmRequest other) {
        if (other == AlgorithmServiceOuterClass.AlgorithmRequest.getDefaultInstance()) return this;
        if (!other.getJsonInput().isEmpty()) {
          jsonInput_ = other.jsonInput_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                jsonInput_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object jsonInput_ = "";
      /**
       * <code>string json_input = 1;</code>
       * @return The jsonInput.
       */
      public java.lang.String getJsonInput() {
        java.lang.Object ref = jsonInput_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonInput_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string json_input = 1;</code>
       * @return The bytes for jsonInput.
       */
      public com.google.protobuf.ByteString
          getJsonInputBytes() {
        java.lang.Object ref = jsonInput_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonInput_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string json_input = 1;</code>
       * @param value The jsonInput to set.
       * @return This builder for chaining.
       */
      public Builder setJsonInput(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jsonInput_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string json_input = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJsonInput() {
        jsonInput_ = getDefaultInstance().getJsonInput();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string json_input = 1;</code>
       * @param value The bytes for jsonInput to set.
       * @return This builder for chaining.
       */
      public Builder setJsonInputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jsonInput_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:algorithm.AlgorithmRequest)
    }

    // @@protoc_insertion_point(class_scope:algorithm.AlgorithmRequest)
    private static final AlgorithmServiceOuterClass.AlgorithmRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AlgorithmServiceOuterClass.AlgorithmRequest();
    }

    public static AlgorithmServiceOuterClass.AlgorithmRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlgorithmRequest>
        PARSER = new com.google.protobuf.AbstractParser<AlgorithmRequest>() {
      @java.lang.Override
      public AlgorithmRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AlgorithmRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlgorithmRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AlgorithmServiceOuterClass.AlgorithmRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlgorithmResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:algorithm.AlgorithmResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string json_output = 1;</code>
     * @return The jsonOutput.
     */
    java.lang.String getJsonOutput();
    /**
     * <code>string json_output = 1;</code>
     * @return The bytes for jsonOutput.
     */
    com.google.protobuf.ByteString
        getJsonOutputBytes();
  }
  /**
   * Protobuf type {@code algorithm.AlgorithmResponse}
   */
  public static final class AlgorithmResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:algorithm.AlgorithmResponse)
      AlgorithmResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlgorithmResponse.newBuilder() to construct.
    private AlgorithmResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlgorithmResponse() {
      jsonOutput_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new AlgorithmResponse();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              AlgorithmServiceOuterClass.AlgorithmResponse.class, AlgorithmServiceOuterClass.AlgorithmResponse.Builder.class);
    }

    public static final int JSON_OUTPUT_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object jsonOutput_ = "";
    /**
     * <code>string json_output = 1;</code>
     * @return The jsonOutput.
     */
    @java.lang.Override
    public java.lang.String getJsonOutput() {
      java.lang.Object ref = jsonOutput_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        jsonOutput_ = s;
        return s;
      }
    }
    /**
     * <code>string json_output = 1;</code>
     * @return The bytes for jsonOutput.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getJsonOutputBytes() {
      java.lang.Object ref = jsonOutput_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        jsonOutput_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonOutput_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, jsonOutput_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(jsonOutput_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, jsonOutput_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof AlgorithmServiceOuterClass.AlgorithmResponse)) {
        return super.equals(obj);
      }
      AlgorithmServiceOuterClass.AlgorithmResponse other = (AlgorithmServiceOuterClass.AlgorithmResponse) obj;

      if (!getJsonOutput()
          .equals(other.getJsonOutput())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + JSON_OUTPUT_FIELD_NUMBER;
      hash = (53 * hash) + getJsonOutput().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static AlgorithmServiceOuterClass.AlgorithmResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static AlgorithmServiceOuterClass.AlgorithmResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static AlgorithmServiceOuterClass.AlgorithmResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(AlgorithmServiceOuterClass.AlgorithmResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code algorithm.AlgorithmResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:algorithm.AlgorithmResponse)
        AlgorithmServiceOuterClass.AlgorithmResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                AlgorithmServiceOuterClass.AlgorithmResponse.class, AlgorithmServiceOuterClass.AlgorithmResponse.Builder.class);
      }

      // Construct using org.example.madeinha.global.gRPC.AlgorithmServiceOuterClass.AlgorithmResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        jsonOutput_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return AlgorithmServiceOuterClass.internal_static_algorithm_AlgorithmResponse_descriptor;
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmResponse getDefaultInstanceForType() {
        return AlgorithmServiceOuterClass.AlgorithmResponse.getDefaultInstance();
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmResponse build() {
        AlgorithmServiceOuterClass.AlgorithmResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public AlgorithmServiceOuterClass.AlgorithmResponse buildPartial() {
        AlgorithmServiceOuterClass.AlgorithmResponse result = new AlgorithmServiceOuterClass.AlgorithmResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(AlgorithmServiceOuterClass.AlgorithmResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.jsonOutput_ = jsonOutput_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof AlgorithmServiceOuterClass.AlgorithmResponse) {
          return mergeFrom((AlgorithmServiceOuterClass.AlgorithmResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(AlgorithmServiceOuterClass.AlgorithmResponse other) {
        if (other == AlgorithmServiceOuterClass.AlgorithmResponse.getDefaultInstance()) return this;
        if (!other.getJsonOutput().isEmpty()) {
          jsonOutput_ = other.jsonOutput_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                jsonOutput_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object jsonOutput_ = "";
      /**
       * <code>string json_output = 1;</code>
       * @return The jsonOutput.
       */
      public java.lang.String getJsonOutput() {
        java.lang.Object ref = jsonOutput_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          jsonOutput_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string json_output = 1;</code>
       * @return The bytes for jsonOutput.
       */
      public com.google.protobuf.ByteString
          getJsonOutputBytes() {
        java.lang.Object ref = jsonOutput_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          jsonOutput_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string json_output = 1;</code>
       * @param value The jsonOutput to set.
       * @return This builder for chaining.
       */
      public Builder setJsonOutput(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        jsonOutput_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string json_output = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearJsonOutput() {
        jsonOutput_ = getDefaultInstance().getJsonOutput();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string json_output = 1;</code>
       * @param value The bytes for jsonOutput to set.
       * @return This builder for chaining.
       */
      public Builder setJsonOutputBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        jsonOutput_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:algorithm.AlgorithmResponse)
    }

    // @@protoc_insertion_point(class_scope:algorithm.AlgorithmResponse)
    private static final AlgorithmServiceOuterClass.AlgorithmResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new AlgorithmServiceOuterClass.AlgorithmResponse();
    }

    public static AlgorithmServiceOuterClass.AlgorithmResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlgorithmResponse>
        PARSER = new com.google.protobuf.AbstractParser<AlgorithmResponse>() {
      @java.lang.Override
      public AlgorithmResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<AlgorithmResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlgorithmResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public AlgorithmServiceOuterClass.AlgorithmResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algorithm_AlgorithmRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algorithm_AlgorithmRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_algorithm_AlgorithmResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_algorithm_AlgorithmResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027algorithm_service.proto\022\talgorithm\"&\n\020" +
      "AlgorithmRequest\022\022\n\njson_input\030\001 \001(\t\"(\n\021" +
      "AlgorithmResponse\022\023\n\013json_output\030\001 \001(\t2\355" +
      "\001\n\020AlgorithmService\022C\n\006DbScan\022\033.algorith" +
      "m.AlgorithmRequest\032\034.algorithm.Algorithm" +
      "Response\022G\n\nconvexHull\022\033.algorithm.Algor" +
      "ithmRequest\032\034.algorithm.AlgorithmRespons" +
      "e\022K\n\016PointInPolygon\022\033.algorithm.Algorith" +
      "mRequest\032\034.algorithm.AlgorithmResponseb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_algorithm_AlgorithmRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_algorithm_AlgorithmRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algorithm_AlgorithmRequest_descriptor,
        new java.lang.String[] { "JsonInput", });
    internal_static_algorithm_AlgorithmResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_algorithm_AlgorithmResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_algorithm_AlgorithmResponse_descriptor,
        new java.lang.String[] { "JsonOutput", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
